import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
test("Jan follows the guided demo, replays a source test, responds; Femke gets 404", async ({ page, browser }, testInfo) => {
  const credentials = JSON.parse(readFileSync(".local/flow-e2e/credentials.json","utf8")) as {jan:string;femke:string};
  const errors: string[] = []; page.on("pageerror",error => errors.push(error.message));
  await page.goto("/login");
  await page.getByLabel("Email",{exact:true}).fill("jan@example.com");
  await page.getByLabel("Password",{exact:true}).fill(credentials.jan);
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Case inbox"})).toBeVisible();
  await expect(page.getByText("Due 18 Feb 2026")).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("01-inbox.png"),fullPage:true});
  await page.getByRole("link").filter({has:page.getByRole("heading",{name:"Piet Peeters"})}).click();
  await expect(page).toHaveURL(/\/cases\/CASE-0001$/);
  await expect(page.getByRole("heading",{name:"The client's message"})).toBeVisible();
  await expect(page.getByText(/Melanie Claes/)).toBeVisible();
  await expect(page.getByLabel("What do you want Trustworx to check?")).toHaveValue(/Why did Piet receive €3,500 instead of €5,000 in January 2026/);
  await expect(page.getByRole("heading",{name:"Attachments"})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("02-question.png"),fullPage:true});
  await page.getByRole("button",{name:"Check with Trustworx"}).click();
  const card = page.locator(".answer-card"), agreed = page.locator("details.check-section").filter({has:page.locator("summary").filter({hasText:"Agreed regime"})});
  await expect(card).toContainText("100%"); await expect(card).toContainText("70%"); await expect(card).toContainText("€1,500");
  const answerText = await card.innerText();
  expect(answerText.match(/100%/g)).toHaveLength(1); expect(answerText.match(/70%/g)).toHaveLength(1);
  expect(answerText.match(/€5,000/g)).toHaveLength(1); expect(answerText.match(/€3,500/g)).toHaveLength(1);
  await expect(page.getByLabel("Remove from this test")).toHaveCount(0);
  const assertPlain = async () => {
    expect(await page.locator("main").innerText()).not.toMatch(/\b(?:REC|DOC|CASE|P|CL|E)-\d{4}\b|\b[a-z]+_[a-z_]+\b|\b\d{4}-\d{2}-\d{2}\b|Open — Open|Authoritative|Supporting evidence|Demo clock pinned/);
  };
  await assertPlain();
  await expect(agreed.locator(".evidence-group").filter({has:page.getByRole("heading",{name:"Counts",exact:true})})).toContainText("Contract, 1 Jan 2026");
  await expect(agreed).toContainText("Starts 1 Mar 2026");
  await expect(agreed.locator(".evidence-group").filter({has:page.getByRole("heading",{name:"Contradicts",exact:true})})).toContainText("HR tool entry");
  await expect(page.getByText(/Copied from Payroll input, January 2026/).first()).toBeVisible();
  await page.screenshot({path:testInfo.outputPath("03-answer.png"),fullPage:true});
  await agreed.getByRole("link",{name:"Contract, 1 Jan 2026",exact:true}).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog")).toContainText("REC-0002");
  await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("tab",{name:"Past cases",exact:true}).click();
  const past = page.getByRole("tabpanel").locator("article");
  await expect(past.nth(0)).toContainText("Outcome confirmed as correct");
  await expect(past.nth(1)).toContainText("Later reversed after a complaint"); await assertPlain();
  await page.getByRole("tab",{name:"People",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Sarah",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Ines",exact:true})).toBeVisible(); await assertPlain();
  await page.getByRole("tab",{name:"Sources",exact:true}).click();
  await page.getByRole("switch",{name:"Test this answer"}).check();
  await agreed.locator(".source-row").filter({has:page.getByRole("link",{name:"Contract, 1 Jan 2026",exact:true})}).getByLabel("Remove from this test").check();
  await expect(card).toContainText("was Backed → now Unconfirmed");
  await expect(agreed.locator("summary")).toContainText("Unconfirmed");
  const replay = page.url(); await page.goto(replay);
  await expect(card).toContainText("was Backed → now Unconfirmed");
  await page.getByRole("button",{name:"Reset",exact:true}).click();
  await expect(agreed.locator("summary")).toContainText("Backed");
  await expect(card).toContainText("100%"); await expect(card).not.toContainText("was Backed");
  await page.getByRole("switch",{name:"Test this answer"}).uncheck();
  await page.getByRole("tab",{name:"Procedure",exact:true}).click();
  await expect(page.getByRole("tabpanel")).toContainText("Sarah");
  await expect(page.getByRole("tabpanel")).toContainText("This procedure says:");
  await expect(page.getByRole("tabpanel").locator("details")).not.toHaveAttribute("open");
  await page.getByText("Not used (2)",{exact:true}).click();
  await expect(page.getByRole("tabpanel")).toContainText("Other country: NL"); await assertPlain();
  await page.getByRole("link",{name:"Prepare reply"}).click();
  await expect(page.getByRole("heading",{name:"Reply draft to the client"})).toBeVisible();
  await expect(page.getByLabel("Action")).not.toContainText("Approve correction");
  await expect(page.locator("details").filter({hasText:"Case history"})).not.toHaveAttribute("open");
  await page.getByLabel("Rationale",{exact:true}).fill("Reviewed the contract and requested payroll lead confirmation.");
  await page.getByRole("button",{name:"Record decision",exact:true}).click();
  await expect(page.getByRole("status").filter({hasText:"Decision recorded."})).toBeVisible();
  await page.getByText("Case history",{exact:true}).click();
  await expect(page.locator(".timeline")).toContainText("Reviewed the contract");
  await page.screenshot({path:testInfo.outputPath("04-respond.png"),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const other = await browser.newContext(); const femke = await other.newPage();
  await femke.goto("http://127.0.0.1:3115/login");
  await femke.getByLabel("Email",{exact:true}).fill("femke@example.com"); await femke.getByLabel("Password",{exact:true}).fill(credentials.femke);
  await femke.getByRole("button",{name:"Sign in",exact:true}).click(); await expect(femke).toHaveURL(/\/cases$/);
  for (const suffix of ["","/answer","/respond"]) expect((await femke.goto(`http://127.0.0.1:3115/cases/CASE-0001${suffix}`))?.status()).toBe(404);
  await other.close(); expect(errors).toEqual([]);
});
