"use client";
import Link from "next/link";
import { useTransition, ViewTransition } from "react";
import { useRouter } from "next/navigation";
import type { FlowData } from "../server/services/flow.ts";
import type { Source } from "../data/normalized.ts";
import type { EvidenceRef } from "../engine/types.ts";
import type { Draft } from "../ai/templates.ts";
import { flowUrl, type FlowQuery } from "./flow-query.ts";
import { copy, flowCopy, defaultAsk, humanText, claimText, calculationText, periodText, findingValue, scanText, sourceReason, sourceName, reasonText, vocabularyText, changeText, testingText } from "./copy.ts";
import { Badge } from "./Badge.tsx";
import { CopyButton } from "./CopyButton.tsx";
import { Highlight, SourceLink, SourceDrawer } from "./SourceDrawer.tsx";
export function Answer({ data, questions }: { data: FlowData; questions: { id: string; draft: Draft }[] }) {
  const { analysis:a } = data.result, c = a.context.case, query = data.query, router = useRouter();
  const [pending, transition] = useTransition();
  const testing = query.test === "1" || a.excludedSourceIds.length > 0;
  const toggle = (id: string) => { const ids = new Set(a.excludedSourceIds); if (ids.has(id)) ids.delete(id); else ids.add(id); update({exclude:[...ids].sort().join(","),test:"1"}); };
  const changed = (id: string) => { const diff = data.result.diff.findings.find(f => f.id === id); return diff ? <p className="change">{changeText(diff.before.state,diff.after.state)}</p> : null; };
  const update = (patch: Partial<FlowQuery>) => transition(() => router.push(flowUrl(c.id,"answer",query,patch),{scroll:false}));
  const main = a.findings.filter(f => f.attribute === "work_regime_pct").sort((x,y) => Number(y.id === query.ask)-Number(x.id === query.ask));
  const expanded = query.checks?.split(",").find(id => a.findings.some(f => f.id === id));
  const count = (refs: EvidenceRef[]) => new Set(refs.map(r => a.evidenceIndex[r.evidenceId].source.id)).size;
  const checked = new Set([...Object.values(a.evidenceIndex).map(e => e.source.id), ...(a.procedure.selected ? [a.procedure.selected.id] : []), ...a.procedure.notApplicable.map(p => p.source.id)]).size;
  const ask = flowCopy.questions[query.ask] || (query.ask === "procedure" ? flowCopy.procedureQuestion : query.ask) || defaultAsk(c,a.context.employee.name);
  const chips = (refs: EvidenceRef[]) => [...new Map(refs.map(ref => { const source = a.evidenceIndex[ref.evidenceId].source; return [source.id,source]; })).values()].map(source => <SourceLink key={source.id} source={source} data={data} step="answer" />);
  const lineage = (source: Source, copied: boolean) => source.kind === "record" && source.data.derived_from.map(id => data.presentation.sourceNames[id]).filter(Boolean).map(parent => <span key={parent.id}>{copied ? flowCopy.copiedFrom : flowCopy.takenFrom} {humanText(sourceName(parent))}{copied ? `, ${flowCopy.notIndependent}.` : "."} </span>);
  const row = (source: Source, reasons: string[] = [], ref?: EvidenceRef) => {
    const assertion = ref ? a.evidenceIndex[ref.evidenceId].assertion : undefined;
    return <div className="source-row" key={ref?.evidenceId || source.id}><SourceLink source={source} data={data} step="answer" /><p className="muted">{source.kind === "record" ? source.data.system : data.presentation.names[source.data.owner || ""] || copy.noOwner}</p>{reasons.length > 0 && <div className="chips">{reasons.map(reason => <span className="chip" key={reason}>{sourceReason(reason,source,c,assertion?.validFrom,assertion?.validTo)}</span>)}</div>}<p className="small">{lineage(source,true)}</p>{testing && <label className="check-label"><input type="checkbox" checked={a.excludedSourceIds.includes(source.id)} disabled={pending} onChange={() => toggle(source.id)} />{flowCopy.remove}</label>}</div>;
  };
  const selected = a.procedure.selected;
  const tabs = Object.keys(flowCopy.tabs) as (keyof typeof flowCopy.tabs)[];
  return <>{testing && <aside className="whatif" role="status"><strong>{testingText(a.excludedSourceIds.length)}</strong><button disabled={pending} onClick={() => update({exclude:"",test:"1"})}>{copy.reset}</button>{pending && <span>{copy.updating}</span>}</aside>}<div><h1 className="eyebrow">{flowCopy.asked}</h1><p>{humanText(ask)}</p></div><p className="muted" data-testid="scan-line">{scanText(checked,count(a.findings.flatMap(f => [...f.authoritative,...f.supporting])),count(a.findings.flatMap(f => f.notApplicable)),count(a.findings.flatMap(f => f.contradicting)))}</p>
    <section className="panel stack answer-card" aria-labelledby="answer-title"><div className="row between wrap"><h2 id="answer-title">{flowCopy.answer}</h2><label className="check-label"><input type="checkbox" role="switch" checked={testing} disabled={pending} onChange={() => update({test:testing ? "0" : "1",exclude:""})} />{flowCopy.test}</label></div>{main.map(f => <div className="claim stack-tight" key={f.id}><p>{claimText(f,a.context.employee.name,periodText(c))}</p>{changed(f.id)}<div className="chips">{chips(f.authoritative.length ? f.authoritative : f.supporting)}<Badge state={f.state} /></div>{[...f.authoritative,...f.supporting].filter((ref,i,refs) => refs.findIndex(r => a.evidenceIndex[r.evidenceId].source.id === a.evidenceIndex[ref.evidenceId].source.id) === i).map(ref => <p className="small" key={ref.evidenceId}>{lineage(a.evidenceIndex[ref.evidenceId].source,false)}</p>)}</div>)}{a.derivations.map(d => <div className="stack-tight" key={d.id}><p>{calculationText(d)}</p><div className="chips">{chips(d.evidenceIds.map(evidenceId => ({evidenceId,reasons:[]})))}</div></div>)}{a.gaps.length > 0 && <aside className="notice"><h3>{flowCopy.beforeAct}</h3><ul>{[...new Set(a.gaps.map(g => flowCopy.gaps[g.code] || reasonText(g.code)))].slice(0,3).map(text => <li key={text}>{text}</li>)}</ul></aside>}</section>
    <section className="panel stack"><div className="tabs" role="tablist" aria-label={copy.sources}>{tabs.map((tab,index) => <Link key={tab} id={`tab-${tab}`} role="tab" aria-selected={query.tab === tab} tabIndex={query.tab === tab ? 0 : -1} aria-controls="answer-panel" href={flowUrl(c.id,"answer",query,{tab})} scroll={false} onKeyDown={event => { const next = event.key === "ArrowRight" ? (index+1)%tabs.length : event.key === "ArrowLeft" ? (index+tabs.length-1)%tabs.length : event.key === "Home" ? 0 : event.key === "End" ? tabs.length-1 : -1; if (next >= 0) { event.preventDefault(); document.getElementById(`tab-${tabs[next]}`)?.focus(); update({tab:tabs[next]}); } }}>{flowCopy.tabs[tab]}</Link>)}</div><ViewTransition key={query.tab} name="answer-tab" default="none" enter="quick-fade" exit="quick-fade" share="quick-fade"><div id="answer-panel" role="tabpanel" aria-labelledby={`tab-${query.tab}`}>
      {query.tab === "sources" && <div className="stack">{a.findings.map(f => <details className="check-section" key={f.id} open={expanded === f.id}><summary onClick={event => { event.preventDefault(); update({checks:expanded === f.id ? "" : f.id}); }}><span>{flowCopy.checks[f.id] || humanText(f.question)}</span><Badge state={f.state} /><strong>{findingValue(f)}</strong></summary>{changed(f.id)}<p className="muted">{flowCopy.questions[f.id] || humanText(f.question)}</p>{[{label:copy.counts,refs:[...f.authoritative,...f.supporting]}, {label:copy.contradicts,refs:f.contradicting}, {label:copy.doesntApply,refs:f.notApplicable}].filter(group => group.refs.length).map(group => <section className="evidence-group" key={group.label}><h3>{group.label}</h3>{group.refs.map(ref => row(a.evidenceIndex[ref.evidenceId].source,group.label === copy.doesntApply ? ref.reasons : [],ref))}</section>)}</details>)}</div>}
      {query.tab === "past" && <div className="cards">{a.precedents.slice(0,3).map(p => <article className="subpanel stack-tight" key={p.id}><h3>{vocabularyText("root_causes",p.root_cause)}</h3><span className="small muted">{flowCopy.anonymised}</span>{p.flags.includes("later_reversed") && <><span className="badge conflicting">⇄ {flowCopy.reversed}</span><p>{flowCopy.reversedHint}</p></>}<p>{humanText(p.summary || copy.summarySuppressed)}</p><p>{flowCopy.resolvedBy} {data.presentation.names[p.decided_by] || flowCopy.personUnknown} · {vocabularyText("outcome_statuses",p.outcome.status)}</p>{p.matchReasons.length > 0 && <p>{flowCopy.similar}: {p.matchReasons.map(reasonText).join(", ")}</p>}{p.differences.length > 0 && <p>{flowCopy.different}: {p.differences.map(reasonText).join(", ")}</p>}</article>)}{!a.precedents.length && <p>{copy.noResults}</p>}</div>}
      {query.tab === "people" && <div className="cards">{a.experts.slice(0,3).map(e => { const text = humanText(questions.find(q => q.id === e.person.id)?.draft.sentences.map(s => s.text).join(" ") || ""); return <article className="subpanel stack" key={e.person.id}><h3>{e.person.name}</h3><p className="muted">{vocabularyText("roles",e.person.role)}</p><ul>{e.reasons.map(reason => <li key={reason}>{reasonText(reason)}</li>)}</ul>{text && <><p>{text}</p><CopyButton text={text} /></>}</article>; })}{!a.experts.length && <p>{copy.noResults}</p>}</div>}
      {query.tab === "procedure" && <div className="stack">{selected?.kind === "document" ? <><div className="row between"><h3>{humanText(selected.data.title)}</h3><span className="badge">{flowCopy.current}</span></div><p className="muted">{data.presentation.names[selected.data.owner || ""] || copy.noOwner}{selected.data.version && <> · {copy.version} {selected.data.version}</>}</p>{row(selected)}<Highlight text={humanText(selected.data.body)} quotes={selected.data.body.split(/\r?\n/).filter(line => /^\d+\./.test(line)).slice(0,2).map(humanText)} /><p><strong>{flowCopy.procedureSays}</strong> {flowCopy.stepsText[a.nextStep.id] || humanText(a.nextStep.label)}</p></> : <p>{flowCopy.unavailableProcedure}</p>}{a.procedure.notApplicable.length > 0 && <details open={query.unused === "1"}><summary onClick={event => { event.preventDefault(); update({unused:query.unused === "1" ? "0" : "1"}); }}>{flowCopy.unused} ({a.procedure.notApplicable.length})</summary>{a.procedure.notApplicable.map(p => row(p.source,p.reasons))}</details>}</div>}
    </div></ViewTransition></section><div className="answer-actions"><Link className="primary check-button" href={flowUrl(c.id,"respond",query,{source:undefined})}><span>{flowCopy.prepare}</span><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false"><path d="M5 12h14m-6-6 6 6-6 6" /></svg></Link></div><SourceDrawer data={data} step="answer" /></>;
}
