"use client";
import Link from "next/link";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { EvidenceRef, State } from "../engine/types.ts";
import type { Source } from "../data/normalized.ts";
import type { User } from "../server/repo/index.ts";
import type { getAnalysis } from "../server/services/analysis.ts";
import type { Draft } from "../ai/templates.ts";
import { copy, displayDate, money, reasonText } from "./copy.ts";
import { Logout } from "./Login.tsx";
type Result = ReturnType<typeof getAnalysis>;
function Badge({ state }: { state: State }) { return <span className={`badge ${state.toLowerCase()}`}><span aria-hidden="true">{{ SUPPORTED: "✓", INDICATION: "◐", CONFLICTING: "⇄", INSUFFICIENT: "?" }[state]}</span> {copy.states[state]}</span>; }
function Reasons({ reasons }: { reasons: string[] }) { return <span className="chips">{reasons.map(reason => <span className="chip" key={reason}>{reasonText(reason)}</span>)}</span>; }
function CopyButton({ text }: { text: string }) { const [message, setMessage] = useState(""); return <span className="row"><button onClick={async () => { try { await navigator.clipboard.writeText(text); setMessage(copy.copied); } catch { setMessage(copy.copyFailed); } }}>{copy.copy}</button><span role="status">{message}</span></span>; }
export function AsOf({ asOf, demoClock }: { asOf: string; demoClock: boolean }) { return <p className="asof">{copy.asOf}: <time dateTime={asOf}>{displayDate(asOf)}</time> · {demoClock ? copy.demoClock : copy.liveClock}</p>; }
function Highlight({ text, quotes }: { text: string; quotes: string[] }) {
  const ranges = quotes.flatMap(quote => { const index = text.indexOf(quote); return index < 0 ? [] : [{ start: index, end: index + quote.length }]; }).sort((a,b) => a.start - b.start);
  let end = 0; const pieces: React.ReactNode[] = [];
  for (const range of ranges) { if (range.start < end) continue; pieces.push(text.slice(end, range.start), <mark key={range.start}>{text.slice(range.start, range.end)}</mark>); end = range.end; }
  pieces.push(text.slice(end)); return <div className="source-body">{pieces}</div>;
}
export function Dossier({ result, user, reply, explanation, expertQuestions }: { result: Result; user: User; reply: Draft; explanation: Draft; expertQuestions: { id: string; draft: Draft }[] }) {
  const { analysis: a } = result, router = useRouter();
  const [selected, setSelected] = useState(a.findings[0]?.id || ""), [tab, setTab] = useState<keyof typeof copy.tabs>("Precedents"), [source, setSource] = useState<Source | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [pending, transition] = useTransition();
  const dialog = useRef<HTMLDialogElement>(null), finding = a.findings.find(f => f.id === selected) || a.findings[0];
  const open = (value: Source) => { setSource(value); dialog.current?.showModal(); };
  const toggle = (id: string) => { const excluded = new Set(a.excludedSourceIds); if (excluded.has(id)) excluded.delete(id); else excluded.add(id); transition(() => router.push(`/cases/${a.context.case.id}${excluded.size ? `?exclude=${encodeURIComponent([...excluded].sort().join(","))}` : ""}`, { scroll: false })); };
  const reset = () => transition(() => router.push(`/cases/${a.context.case.id}`, { scroll: false }));
  const groups: { label: string; refs: EvidenceRef[] }[] = finding ? [{ label: copy.counts, refs: finding.authoritative }, { label: copy.supports, refs: finding.supporting }, { label: copy.contradicts, refs: finding.contradicting }, { label: copy.doesntApply, refs: finding.notApplicable }, { label: copy.ignored, refs: finding.ignored }] : [];
  const sourceRow = (value: Source, reasons: string[] = []) => <div className="source-row"><div className="stack-tight"><button className="text-button" onClick={() => open(value)}>{value.id} · {value.kind === "document" ? value.data.title : value.data.system}</button><Reasons reasons={reasons} /><span className="small muted">{value.data.valid_from || copy.openEnded} — {value.data.valid_to || copy.openEnded}</span></div><label className="check-label"><input type="checkbox" checked={a.excludedSourceIds.includes(value.id)} disabled={pending} onChange={() => toggle(value.id)} />{copy.exclude}</label></div>;
  const stages = result.correction.stage;
  const actions: (keyof typeof copy.actions)[] = ["record", "send_explanation", "request_confirmation", ...(stages === "none" ? ["propose_correction" as const] : []), ...(stages === "proposed" && user.role === "payroll_lead" && result.correction.proposedBy !== user.personId ? ["approve_correction" as const] : []), ...(stages === "approved" ? ["mark_executed" as const] : []), ...(stages === "executed" ? ["confirm_outcome" as const] : [])];
  const timeline = [...a.context.case.timeline.map((event, i) => ({ id: `source-${i}`, at: event.at, text: event.description, actor: event.actor_id })), ...result.decisions.map(d => ({ id: d.id, at: d.at, text: `${copy.actions[d.action as keyof typeof copy.actions] || d.action}: ${d.rationale}`, actor: d.actor_id }))].sort((x,y) => x.at.localeCompare(y.at));
  return <><header className="topbar"><Link href="/cases" className="brand">{copy.app}</Link><div className="row"><Link href="/cases">{copy.back}</Link><Logout /></div></header>
    {a.excludedSourceIds.length > 0 && <aside className="whatif" role="status"><strong>{copy.whatIf}: {a.excludedSourceIds.length} {copy.excluded}</strong><span>{result.diff.findings.map(f => `${copy.states[f.before.state]} → ${copy.states[f.after.state]}`).join(" · ")}</span><button disabled={pending} onClick={reset}>{copy.reset}</button>{pending && <span>{copy.updating}</span>}</aside>}
    <main className="shell stack" aria-busy={pending}><header className="stack-tight"><p className="eyebrow">{a.context.case.id} · {a.context.client.name}</p><h1>{a.context.employee.name}</h1><blockquote>{a.context.case.question_text}</blockquote><div className="row wrap"><span>{copy.period}: {a.context.case.disputed_period.from} — {a.context.case.disputed_period.to}</span>{a.context.case.reported && <span>{copy.reported}: {a.context.case.reported.expected_amount !== undefined ? money(a.context.case.reported.expected_amount) : "—"} / {a.context.case.reported.received_amount !== undefined ? money(a.context.case.reported.received_amount) : "—"} ({copy[a.context.case.reported.basis]})</span>}</div><AsOf asOf={a.asOf} demoClock={result.demoClock} /></header>
    <section className="key-card stack-tight"><p className="eyebrow">{copy.keyFinding}</p><h2>{copy.outcomeText[a.outcome as keyof typeof copy.outcomeText] || copy.noValue}</h2>{a.comparisons[0] && <p>{copy.agreed}: <strong>{String(a.findings.find(f => f.id === a.comparisons[0].left)?.value ?? "—")}%</strong> · {copy.processed}: <strong>{String(a.findings.find(f => f.id === a.comparisons[0].right)?.value ?? "—")}%</strong></p>}<p><strong>{copy.nextStep}:</strong> {a.nextStep.label} · {a.nextStep.ownerRole.replaceAll("_", " ")}</p><a href="#open-items">{a.gaps.length} {copy.openItems.toLowerCase()}</a></section>
    <div className="dossier-grid"><div className="stack"><section className="panel"><h2>{copy.findings}</h2><div className="finding-list">{a.findings.map(f => <article key={f.id} className={`finding ${selected === f.id ? "selected" : ""}`}><button className="finding-select" onClick={() => setSelected(f.id)}><span>{f.question}</span><Badge state={f.state} /><strong>{f.value === null ? copy.noValue : `${String(f.value)}${f.attribute === "work_regime_pct" ? "%" : " EUR"}`}</strong></button><Reasons reasons={f.reasons} /><div className="row wrap small"><span>{copy.basedOn}:</span>{[...f.authoritative, ...f.supporting].map(ref => <button key={ref.evidenceId} onClick={() => open(a.evidenceIndex[ref.evidenceId].source)}>{a.evidenceIndex[ref.evidenceId].source.id}</button>)}<button className="text-button" onClick={() => setSelected(f.id)}>{copy.doesntCount}: {f.notApplicable.length}</button></div>{result.diff.findings.filter(d => d.id === f.id).map(d => <p className="change" key={d.id}>{copy.states[d.before.state]} → {copy.states[d.after.state]}</p>)}</article>)}</div></section>
      <section className="panel stack"><h2>{copy.comparison}</h2><div className="table-wrap"><table><thead><tr><th>{copy.agreed}</th><th>{copy.processed}</th><th>{copy.outcome}</th></tr></thead><tbody>{a.comparisons.map(c => <tr key={c.id}><td>{String(a.findings.find(f => f.id === c.left)?.value ?? "—")}%</td><td>{String(a.findings.find(f => f.id === c.right)?.value ?? "—")}%</td><td><Reasons reasons={c.reasons} /></td></tr>)}</tbody></table></div><h3>{copy.derivation}</h3>{a.derivations.map(d => <div key={d.id}>{d.expectedAtProcessed !== undefined ? <p className="derivation">{money(d.reference!)} × {d.processedRegime}% = {money(d.expectedAtProcessed)} · {d.status === "explains_paid_amount" ? copy.explainsPaid : copy.notExplainsPaid}{d.gap !== undefined && <> · {copy.gap}: <strong>{money(d.gap)}</strong></>}</p> : <Reasons reasons={d.reasons} />}</div>)}</section>
      <section className="panel stack-tight"><h2>{copy.procedure}</h2>{a.procedure.selected ? sourceRow(a.procedure.selected) : <p>{copy.noProcedure}</p>}<details><summary>{copy.otherProcedures} ({a.procedure.notApplicable.length})</summary>{a.procedure.notApplicable.map(p => <div key={p.source.id}>{sourceRow(p.source, p.reasons)}</div>)}</details></section>
      <section id="open-items" className="panel"><h2>{copy.openItems} ({a.gaps.length})</h2>{a.gaps.length ? <ul>{a.gaps.map((gap,i) => <li key={i}>{reasonText(gap.code)}{gap.findingId && <> · {a.findings.find(f => f.id === gap.findingId)?.question}</>}</li>)}</ul> : <p>{copy.none}</p>}</section>
    </div><aside className="panel source-panel stack"><div><p className="eyebrow">{copy.sources}</p><h2>{finding?.question}</h2></div>{groups.map(group => <section key={group.label} className={group.label === copy.doesntApply ? "muted-sources" : ""}><h3>{group.label} ({group.refs.length})</h3>{group.refs.length ? group.refs.map(ref => <div key={ref.evidenceId}>{sourceRow(a.evidenceIndex[ref.evidenceId].source, ref.reasons)}</div>) : <p className="small muted">{copy.noEvidence}</p>}</section>)}</aside></div>
    <section className="panel stack"><div className="tabs" role="tablist" aria-label={copy.app}>{Object.keys(copy.tabs).map(key => <button key={key} role="tab" id={`tab-${key.replaceAll(" ", "-")}`} aria-selected={tab === key} aria-controls="dossier-tab" onClick={() => setTab(key as keyof typeof copy.tabs)}>{copy.tabs[key as keyof typeof copy.tabs]}</button>)}</div><div role="tabpanel" id="dossier-tab" aria-labelledby={`tab-${tab.replaceAll(" ", "-")}`}>
      {tab === "Precedents" && <div className="cards">{a.precedents.length ? a.precedents.map(p => <article className="subpanel stack-tight" key={p.id}><div className="row wrap"><h3>{p.root_cause.replaceAll("_", " ")}</h3>{p.anonymised && <span className="chip">{copy.anonymised}</span>}{p.flags.length > 0 && <span className="badge conflicting">{copy.laterReversed}</span>}</div><p>{p.summary || copy.summarySuppressed}</p><p className="small">{p.decided_by} · {p.outcome.status.replaceAll("_", " ")}</p><p>{copy.matches}</p><Reasons reasons={p.matchReasons} /><p>{copy.differs}</p><Reasons reasons={p.differences} /></article>) : <p>{copy.noResults}</p>}</div>}
      {tab === "Experts" && <div className="cards">{a.experts.map(e => { const text = expertQuestions.find(q => q.id === e.person.id)?.draft.sentences.map(s => s.text).join(" ") || ""; return <article className="subpanel stack" key={e.person.id}><h3>{e.person.name}</h3><p className="muted">{e.person.role.replaceAll("_", " ")}</p><Reasons reasons={e.reasons} /><p>{text}</p><CopyButton text={text} /></article>; })}</div>}
      {tab === "Timeline" && (timeline.length ? <ol className="timeline">{timeline.map(event => <li key={event.id}><time dateTime={event.at}>{displayDate(event.at)}</time><p>{event.text}</p><small>{event.actor}</small></li>)}</ol> : <p>{copy.noHistory}</p>)}
      {tab === "Reply draft" && <div className="stack"><div className="row"><span className="badge">{copy.template}</span><CopyButton text={reply.sentences.map(s => s.text).join("\n\n")} /></div><p className="muted">{copy.draftHint}</p>{reply.sentences.map((s,i) => <div key={i} className={s.kind === "uncertainty" ? "uncertainty" : "draft-sentence"} tabIndex={0}><p>{s.text}</p><div className="citation-chips">{s.evidenceIds.map(id => <button key={id} onClick={() => open(a.evidenceIndex[id].source)}>{a.evidenceIndex[id].source.id}</button>)}</div></div>)}</div>}
      {tab === "Decision" && <div className="stack"><p>{copy.decisionHint}</p><div className="chips"><span className="chip">{copy.stages[stages]}</span>{result.decisions.some(d => d.action === "send_explanation") && <span className="chip">{copy.replySent}</span>}{["approved", "executed", "confirmed"].includes(stages) && <span className="chip">{copy.correctionApproved}</span>}{["executed", "confirmed"].includes(stages) && <span className="chip">{copy.correctionExecuted}</span>}{stages === "confirmed" && <span className="chip">{copy.outcomeConfirmed}</span>}</div><form className="stack" onSubmit={async event => {
        event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget, data = new FormData(form);
        try { const response = await fetch(`/api/cases/${a.context.case.id}/decisions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: data.get("action"), rationale: data.get("rationale") }) }); if (!response.ok) { setError(response.status === 403 ? copy.approvalDenied : response.status === 409 ? copy.invalidTransition : copy.requestFailed); } else { form.reset(); setError(copy.saved); router.refresh(); } } catch { setError(copy.requestFailed); } finally { setBusy(false); }
      }}><label>{copy.action}<select name="action">{actions.map(action => <option value={action} key={action}>{copy.actions[action]}</option>)}</select></label><label>{copy.rationale}<textarea name="rationale" rows={4} required maxLength={4000} /></label><button className="primary" disabled={busy}>{busy ? copy.recording : copy.record}</button><p role="status">{error}</p></form></div>}
    </div></section><details className="panel"><summary>{copy.keyFinding} · {copy.template}</summary>{explanation.sentences.map((s,i) => <p key={i}>{s.text}</p>)}</details></main>
    <dialog ref={dialog} className="source-dialog"><div className="stack"><div className="row between"><h2>{source?.id}</h2><button onClick={() => dialog.current?.close()}>{copy.close}</button></div>{source && <><h3>{source.kind === "document" ? source.data.title : source.data.system}</h3><dl className="metadata"><dt>{copy.sourceType}</dt><dd>{source.data.type}</dd><dt>{copy.owner}</dt><dd>{source.kind === "record" ? source.data.system : source.data.owner || copy.noOwner}</dd><dt>{copy.status}</dt><dd>{source.data.status}</dd><dt>{copy.version}</dt><dd>{source.kind === "document" ? source.data.version || "—" : "—"}</dd><dt>{copy.validity}</dt><dd>{source.data.valid_from || copy.openEnded} — {source.data.valid_to || copy.openEnded}</dd><dt>{copy.knownAt}</dt><dd>{displayDate(source.data.known_at)}</dd><dt>{copy.visibility}</dt><dd>{source.data.visibility.replaceAll("_", " ")}</dd></dl>{Object.values(a.evidenceIndex).find(e => e.source.id === source.id)?.sameOriginAs.length ? <p className="notice">{copy.sameOrigin}: {Object.values(a.evidenceIndex).find(e => e.source.id === source.id)?.sameOriginAs.join(", ")}</p> : null}{source.kind === "document" ? <Highlight text={source.data.body} quotes={source.data.assertions.map(assertion => assertion.quote)} /> : <table><thead><tr><th>{copy.field}</th><th>{copy.value}</th></tr></thead><tbody>{source.data.facts.map((fact,i) => <tr key={i}><td>{fact.attribute}</td><td>{String(fact.value)}</td></tr>)}</tbody></table>}{source.kind === "record" && source.data.note && <p>{source.data.note}</p>}</>}</div></dialog>
  </>;
}
