"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { FlowData } from "../server/services/flow.ts";
import type { Draft } from "../ai/templates.ts";
import { copy, flowCopy, humanText, shortDate, testingText } from "./copy.ts";
import { flowUrl } from "./flow-query.ts";
import { CopyButton } from "./CopyButton.tsx";
import { SourceDrawer, SourceLink } from "./SourceDrawer.tsx";
export function Respond({ data, reply }: { data: FlowData; reply: Draft }) {
  const { result,user,query } = data, a = result.analysis, c = a.context.case, stage = result.correction.stage, router = useRouter();
  const [busy,setBusy] = useState(false), [message,setMessage] = useState("");
  const actions: (keyof typeof copy.actions)[] = ["record","send_explanation","request_confirmation",...(stage === "none" ? ["propose_correction" as const] : []),...(stage === "proposed" && user.role === "payroll_lead" && result.correction.proposedBy !== user.personId ? ["approve_correction" as const] : []),...(stage === "approved" ? ["mark_executed" as const] : []),...(stage === "executed" ? ["confirm_outcome" as const] : [])];
  const timeline = [...c.timeline.map((event,i) => ({id:`event-${i}`,at:event.at,text:humanText(event.description),actor:data.presentation.names[event.actor_id]})), ...result.decisions.map(d => ({id:d.id,at:d.at,text:`${copy.actions[d.action as keyof typeof copy.actions] || copy.record}: ${humanText(d.rationale)}`,actor:undefined}))].sort((x,y) => x.at.localeCompare(y.at));
  return <>{a.excludedSourceIds.length > 0 && <aside className="notice row wrap"><p>{testingText(a.excludedSourceIds.length)}</p><button onClick={() => router.push(flowUrl(c.id,"respond",query,{exclude:"",test:"0"}))}>{copy.reset}</button></aside>}<section className="panel stack"><div className="row between wrap"><h1>{flowCopy.reply}</h1><span className="badge">{copy.template}</span></div><p className="muted">{copy.draftHint}</p>{reply.sentences.map((sentence,i) => <div className={sentence.kind === "uncertainty" ? "uncertainty" : "draft-sentence"} key={i}><p>{humanText(sentence.text)}</p><div className="chips">{[...new Set(sentence.evidenceIds.map(id => a.evidenceIndex[id]?.source.id).filter(Boolean))].map(id => <SourceLink key={id} source={data.presentation.sourceNames[id]} data={data} step="respond" />)}</div></div>)}<CopyButton text={reply.sentences.map(s => humanText(s.text)).join("\n\n")} /></section>
    <section className="panel stack"><h2>{flowCopy.decision}</h2><p className="muted">{copy.decisionHint}</p><div className="chips"><span className="chip">{copy.stages[stage]}</span>{result.decisions.some(d => d.action === "send_explanation") && <span className="chip">{copy.replySent}</span>}{["approved","executed","confirmed"].includes(stage) && <span className="chip">{copy.correctionApproved}</span>}{["executed","confirmed"].includes(stage) && <span className="chip">{copy.correctionExecuted}</span>}{stage === "confirmed" && <span className="chip">{copy.outcomeConfirmed}</span>}</div>
      <form className="stack" onSubmit={async event => { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget, values = new FormData(form); try { const response = await fetch(`/api/cases/${c.id}/decisions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:values.get("action"),rationale:values.get("rationale")})}); if (!response.ok) setMessage(response.status === 403 ? copy.approvalDenied : response.status === 409 ? copy.invalidTransition : copy.requestFailed); else { form.reset(); setMessage(copy.saved); router.refresh(); } } catch { setMessage(copy.requestFailed); } finally { setBusy(false); } }}><label>{copy.action}<select name="action">{actions.map(action => <option value={action} key={action}>{copy.actions[action]}</option>)}</select></label><label>{copy.rationale}<textarea name="rationale" required maxLength={4000} rows={4} /></label><button className="primary" disabled={busy}>{busy ? copy.recording : copy.record}</button><p role="status">{message}</p></form>
    </section><details className="panel" open={query.history === "1"}><summary onClick={event => { event.preventDefault(); router.push(flowUrl(c.id,"respond",query,{history:query.history === "1" ? "0" : "1"}),{scroll:false}); }}>{flowCopy.history}</summary>{timeline.length ? <ol className="timeline">{timeline.map(event => <li key={event.id}><time dateTime={event.at}>{shortDate(event.at)}</time><p>{event.text}</p>{event.actor && <small>{event.actor}</small>}</li>)}</ol> : <p>{copy.noHistory}</p>}</details><SourceDrawer data={data} step="respond" /></>;
}
